# Generated by Django 3.2.23 on 2024-01-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_text', models.TextField()),
            ],
        ),
    ]
